desc "Generate the app icon in all sizes, as Xcode"
desc "still doesn't do it for you for some reason"
lane :generate_app_icon do
  appicon(
    appicon_devices: [:iphone, :ios_marketing],
    appicon_path: "Major Key/Assets.xcassets"
  )
end

desc "Push a new release build to the App Store"
lane :release do
  match(type: "appstore")
  generate_app_icon

  increment_build_number
  build_app(scheme: "Major Key")

  upload_to_app_store(
    submit_for_review: false,
    force: true
  )
end
