desc "Push a new release build to the App Store"
lane :release do
  # match(type: "appstore")
  appicon(
    appicon_devices: [:iphone, :ios_marketing],
    appicon_path: "Major Key/Assets.xcassets"
  )
  increment_build_number
  build_app(workspace: "Major Key.xcworkspace", scheme: "Major Key")
  upload_to_app_store(submit_for_review: true)
end
