# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X"
])

languages(["en-US"])

# The name of the scheme which contains the UI Tests
scheme("MajorKeyUITests")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)
